# Generated by Django 4.2.7 on 2023-11-26 15:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 26, 15, 58, 50, 882948, tzinfo=datetime.timezone.utc)),
        ),
    ]
